def room(title, capacity, price, total_units, image_url, amenities, description):
    return {
        "title": title,
        "capacity": capacity,
        "price": price,
        "total_units": total_units,
        "image_url": image_url,
        "amenities": amenities,
        "description": description,
    }


# ССЫЛКИ НА ИЗОБРАЖЕНИЯ НОМЕРОВ:
ROOM_BUSINESS_KING = (
    "https://grandpalaceriga.com/wp-content/uploads/2019/10/Business-King_main.jpg"
)
ROOM_BALCONY_SUITE = "https://hotel-aria.com/wp-content/uploads/2024/07/Senior_Suite_s_balkonom_i_pogledom_na_more-Senior_Suite_with_sea_view__balcony_Hotel-Aria-2.jpg"
ROOM_QUIET_STUDIO = (
    "https://lenoxhotelph.com/wp-content/uploads/2017/03/D610IMG-0002-scaled.jpg"
)
ROOM_FAMILY_LOFT = (
    "https://grandtebuhotels.com/wp-content/uploads/2024/08/Family-Loft2-1024x683.jpg"
)
ROOM_RESORT_SUITE = "https://image-tc.galaxy.tf/wijpeg-6255xo0kyr8ijg62a8ybxyjqt/deluxe-king-suite5_standard.jpg?crop=107%2C0%2C1707%2C1280"
ROOM_GARDEN_VILLA = "https://d2e5ushqwiltxm.cloudfront.net/wp-content/uploads/sites/169/2025/11/25065335/03.-Garden-Villa-3-Bedrooms.jpg"


HOTELS_DATA = [
    {
        "name": "The Ritz London",
        "city": "London",
        "country": "United Kingdom",
        "address": "150 Piccadilly, London W1J 9BR",
        "description": "Historic luxury hotel offering classic British elegance and refined service.",
        "hero_image": "https://luxurylondon.co.uk/wp-content/uploads/2022/08/the-ritz-london-3-1.jpg",
        "rating": 4.8,
        "featured": True,
        "rooms": [
            room(
                "Deluxe King",
                2,
                "520.00",
                5,
                ROOM_BUSINESS_KING,
                ["Breakfast", "Spa", "Fast Wi-Fi"],
                "Classic luxury room with elegant interior and king-size bed.",
            ),
            room(
                "Royal Suite",
                3,
                "980.00",
                2,
                ROOM_BALCONY_SUITE,
                ["Breakfast", "Spa", "Airport transfer"],
                "Spacious suite with royal decor and premium amenities.",
            ),
        ],
    },
    {
        "name": "Hilton Almaty",
        "city": "Almaty",
        "country": "Kazakhstan",
        "address": "Esentai Tower, Al-Farabi Avenue 77/7",
        "description": "Modern business hotel with mountain views and premium facilities.",
        "hero_image": "https://www.hilton.com/im/en/ALADTDI/13233599/facade-3.jpg?impolicy=crop&cw=5174&ch=2896&gravity=NorthWest&xposition=0&yposition=168&rw=768&rh=430",
        "rating": 4.7,
        "featured": True,
        "rooms": [
            room(
                "Mountain View King",
                2,
                "210.00",
                6,
                ROOM_BUSINESS_KING,
                ["Breakfast", "Fast Wi-Fi", "Workspace"],
                "Comfortable room with panoramic mountain views.",
            ),
            room(
                "Executive Suite",
                3,
                "390.00",
                3,
                ROOM_RESORT_SUITE,
                ["Spa", "Breakfast", "Workspace"],
                "Executive-level suite with lounge access.",
            ),
        ],
    },
    {
        "name": "Marina Bay Sands",
        "city": "Singapore",
        "country": "Singapore",
        "address": "10 Bayfront Ave, Singapore",
        "description": "Iconic luxury hotel with infinity pool and skyline views.",
        "hero_image": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Marina_Bay_Sands_from_Gardens_by_the_Bay_%28south%29_%288058901371%29.jpg",
        "rating": 4.9,
        "featured": True,
        "rooms": [
            room(
                "Skyline Room",
                2,
                "450.00",
                8,
                ROOM_BUSINESS_KING,
                ["Pool", "Fast Wi-Fi"],
                "Room with breathtaking skyline views.",
            ),
            room(
                "Marina Suite",
                4,
                "900.00",
                3,
                ROOM_RESORT_SUITE,
                ["Pool", "Spa", "Breakfast"],
                "Luxury suite with access to infinity pool.",
            ),
        ],
    },
    {
        "name": "Burj Al Arab",
        "city": "Dubai",
        "country": "United Arab Emirates",
        "address": "Jumeirah St, Dubai",
        "description": "Ultra-luxury hotel known for its sail-shaped architecture.",
        "hero_image": "https://images.euronews.com/articles/stories/09/72/32/62/1536x864_cmsv2_960fd57d-3bd1-5dd3-9e0f-a0770e33d039-9723262.jpg",
        "rating": 5.0,
        "featured": True,
        "rooms": [
            room(
                "Deluxe Suite",
                2,
                "1200.00",
                5,
                ROOM_RESORT_SUITE,
                ["Spa", "Workspace", "Breakfast"],
                "Duplex suite with luxurious interiors.",
            ),
            room(
                "Panoramic Suite",
                4,
                "2200.00",
                2,
                ROOM_GARDEN_VILLA,
                ["Pool", "Spa"],
                "Massive suite with panoramic sea views.",
            ),
        ],
    },
    {
        "name": "Hotel Plaza Athenee",
        "city": "Paris",
        "country": "France",
        "address": "25 Avenue Montaigne, Paris",
        "description": "Elegant Parisian hotel with Eiffel Tower views.",
        "hero_image": "https://upload.wikimedia.org/wikipedia/commons/3/36/Paris_avenue_montaigne_plaza_athena.1.jpg",
        "rating": 4.8,
        "featured": True,
        "rooms": [
            room(
                "Classic Room",
                2,
                "420.00",
                6,
                ROOM_QUIET_STUDIO,
                ["Fast Wi-Fi", "Breakfast"],
                "Cozy Parisian-style room.",
            ),
            room(
                "Eiffel Suite",
                3,
                "850.00",
                2,
                ROOM_BALCONY_SUITE,
                ["Breakfast", "Spa"],
                "Suite with direct Eiffel Tower view.",
            ),
        ],
    },
    {
        "name": "The Peninsula Tokyo",
        "city": "Tokyo",
        "country": "Japan",
        "address": "1-8-1 Yurakucho, Tokyo",
        "description": "Luxury hotel blending modern comfort with Japanese aesthetics.",
        "hero_image": "https://ik.imgkit.net/3vlqs5axxjf/external/https://www.cfmedia.vfmleonardo.com/imageRepo/7/0/128/423/963/PTK_Exterior_Night_Panoramic_Stitched_Cropped_Darkened_O.jpg?tr=w-1200%2Cfo-auto",
        "rating": 4.9,
        "featured": True,
        "rooms": [
            room(
                "Deluxe Room",
                2,
                "400.00",
                7,
                ROOM_QUIET_STUDIO,
                ["Fast Wi-Fi", "Workspace"],
                "Minimalist room with Japanese design.",
            ),
            room(
                "Grand Suite",
                3,
                "800.00",
                3,
                ROOM_RESORT_SUITE,
                ["Spa", "Breakfast"],
                "Spacious suite with city views.",
            ),
        ],
    },
    {
        "name": "The Waldorf Astoria New York",
        "city": "New York",
        "country": "United States",
        "address": "301 Park Ave, New York",
        "description": "Legendary hotel with timeless elegance.",
        "hero_image": "https://www.waldorftowers.nyc/content/uploads/2023/09/001_Exterior-Park-Ave-Side_02_E2-cropped-1580424571.jpg",
        "rating": 4.8,
        "featured": True,
        "rooms": [
            room(
                "Classic King",
                2,
                "350.00",
                10,
                ROOM_BUSINESS_KING,
                ["Fast Wi-Fi", "Breakfast"],
                "Classic New York luxury room.",
            ),
            room(
                "Presidential Suite",
                4,
                "1500.00",
                2,
                ROOM_RESORT_SUITE,
                ["Spa", "Workspace"],
                "Iconic high-end suite.",
            ),
        ],
    },
    {
        "name": "Four Seasons Resort Bali",
        "city": "Bali",
        "country": "Indonesia",
        "address": "Sayan, Ubud, Bali",
        "description": "Tropical resort surrounded by jungle.",
        "hero_image": "https://pix8.agoda.net/hotelImages/48672/-1/60eeceea05cc55b075a410af45ac1ae8.jpg?ce=0&s=1024x",
        "rating": 4.9,
        "featured": True,
        "rooms": [
            room(
                "Garden Villa",
                2,
                "380.00",
                5,
                ROOM_GARDEN_VILLA,
                ["Pool", "Spa"],
                "Private villa with garden.",
            ),
            room(
                "Riverfront Suite",
                3,
                "700.00",
                3,
                ROOM_RESORT_SUITE,
                ["Spa", "Breakfast"],
                "Suite overlooking the river.",
            ),
        ],
    },
    {
        "name": "The Savoy",
        "city": "London",
        "country": "United Kingdom",
        "address": "Strand, London WC2R 0EZ",
        "description": "Luxury hotel with river Thames views.",
        "hero_image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/42/d8/8e/the-iconic-entrance-of.jpg?w=900&h=-1&s=1",
        "rating": 4.8,
        "featured": True,
        "rooms": [
            room(
                "Superior Room",
                2,
                "480.00",
                6,
                ROOM_BUSINESS_KING,
                ["Breakfast"],
                "Elegant room with classic decor.",
            ),
            room(
                "River View Suite",
                3,
                "920.00",
                3,
                ROOM_BALCONY_SUITE,
                ["Spa", "Breakfast"],
                "Suite overlooking Thames.",
            ),
        ],
    },
    {
        "name": "Hotel Arts Barcelona",
        "city": "Barcelona",
        "country": "Spain",
        "address": "Carrer de la Marina, Barcelona",
        "description": "Beachfront hotel with modern luxury.",
        "hero_image": "https://images.trvl-media.com/lodging/1000000/10000/3800/3780/b48fd1ed.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
        "rating": 4.7,
        "featured": False,
        "rooms": [
            room(
                "Sea View Room",
                2,
                "300.00",
                6,
                ROOM_BUSINESS_KING,
                ["Fast Wi-Fi"],
                "Room with Mediterranean view.",
            ),
            room(
                "Luxury Suite",
                3,
                "600.00",
                3,
                ROOM_RESORT_SUITE,
                ["Pool", "Spa"],
                "Suite with premium comfort.",
            ),
        ],
    },
    {
        "name": "Grand Hyatt Seoul",
        "city": "Seoul",
        "country": "South Korea",
        "address": "322 Sowol-ro, Seoul",
        "description": "Modern hotel with panoramic city views.",
        "hero_image": "https://tong.visitkorea.or.kr/cms/resource/40/3097340_image2_1.jpg",
        "rating": 4.7,
        "featured": False,
        "rooms": [
            room(
                "Standard Room",
                2,
                "220.00",
                8,
                ROOM_QUIET_STUDIO,
                ["Fast Wi-Fi"],
                "Simple and modern room.",
            ),
            room(
                "Executive Suite",
                3,
                "450.00",
                3,
                ROOM_RESORT_SUITE,
                ["Spa", "Breakfast"],
                "Executive comfort suite.",
            ),
        ],
    },
    {
        "name": "The Langham Sydney",
        "city": "Sydney",
        "country": "Australia",
        "address": "89-113 Kent St, Sydney",
        "description": "Luxury harbor hotel with refined design.",
        "hero_image": "https://www.langhamhotels.com/content/dam/langhamhotels/dynamicmedia/pacific/the-langham-sydney-tlsyd/home/tlsyd-exterior-01.jpg",
        "rating": 4.8,
        "featured": True,
        "rooms": [
            room(
                "Harbour Room",
                2,
                "310.00",
                5,
                ROOM_BUSINESS_KING,
                ["Fast Wi-Fi"],
                "Room with harbor views.",
            ),
            room(
                "Sydney Suite",
                3,
                "650.00",
                2,
                ROOM_BALCONY_SUITE,
                ["Spa"],
                "Elegant suite with balcony.",
            ),
        ],
    },
    {
        "name": "Shangri-La Bangkok",
        "city": "Bangkok",
        "country": "Thailand",
        "address": "89 Soi Wat Suan Plu, Bangkok",
        "description": "Riverside luxury hotel with Thai hospitality.",
        "hero_image": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/22/dd/a8/a1/shangri-la-bangkok-a.jpg?w=900&h=500&s=1",
        "rating": 4.7,
        "featured": False,
        "rooms": [
            room(
                "River Room",
                2,
                "200.00",
                6,
                ROOM_QUIET_STUDIO,
                ["Fast Wi-Fi"],
                "Room with river view.",
            ),
            room(
                "Krungthep Suite",
                3,
                "420.00",
                3,
                ROOM_RESORT_SUITE,
                ["Spa"],
                "Luxury Thai-style suite.",
            ),
        ],
    },
    {
        "name": "Hotel Adlon Kempinski",
        "city": "Berlin",
        "country": "Germany",
        "address": "Unter den Linden 77, Berlin",
        "description": "Historic luxury hotel near Brandenburg Gate.",
        "hero_image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/684311908.jpg?k=ad3d8c72c1500330225344248f0caa34acd288697b25767941d6265258e2ef6e&o=",
        "rating": 4.8,
        "featured": True,
        "rooms": [
            room(
                "Deluxe Room",
                2,
                "330.00",
                6,
                ROOM_BUSINESS_KING,
                ["Fast Wi-Fi"],
                "Elegant room with classic style.",
            ),
            room(
                "Brandenburg Suite",
                3,
                "700.00",
                2,
                ROOM_BALCONY_SUITE,
                ["Spa"],
                "Suite with landmark views.",
            ),
        ],
    },
    {
        "name": "Fairmont Banff Springs",
        "city": "Banff",
        "country": "Canada",
        "address": "405 Spray Ave, Banff",
        "description": "Castle-style hotel in the Rocky Mountains.",
        "hero_image": "https://images.trvl-media.com/lodging/1000000/20000/13700/13652/9f19f4c3.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill",
        "rating": 4.8,
        "featured": True,
        "rooms": [
            room(
                "Mountain Room",
                2,
                "280.00",
                5,
                ROOM_BUSINESS_KING,
                ["Fast Wi-Fi"],
                "Room with mountain views.",
            ),
            room(
                "Castle Suite",
                4,
                "650.00",
                2,
                ROOM_RESORT_SUITE,
                ["Spa"],
                "Spacious suite in castle style.",
            ),
        ],
    },
]


ROOM_OVERRIDES = {
    "The Ritz London": [
        {"title": "Classic Single", "capacity": 1},
        {"title": "Royal Double", "capacity": 2},
    ],
    "Hilton Almaty": [
        {"title": "Business Single", "capacity": 1},
        {"title": "Mountain Double", "capacity": 2},
    ],
    "Marina Bay Sands": [
        {"title": "Skyline Single", "capacity": 1},
        {"title": "Marina Double", "capacity": 2},
    ],
    "Burj Al Arab": [
        {"title": "Luxury Single Suite", "capacity": 2},
        {"title": "Panoramic Double Suite", "capacity": 3},
    ],
    "Hotel Plaza Athenee": [
        {"title": "Paris Single Room", "capacity": 1},
        {"title": "Balcony Double Room", "capacity": 2},
    ],
    "The Peninsula Tokyo": [
        {"title": "Tokyo Single", "capacity": 1},
        {"title": "Executive Double", "capacity": 2},
    ],
    "The Waldorf Astoria New York": [
        {"title": "Manhattan Single", "capacity": 1},
        {"title": "City Double", "capacity": 2},
    ],
    "Four Seasons Resort Bali": [
        {"title": "Garden Villa Solo", "capacity": 2},
        {"title": "River Villa Family", "capacity": 4},
    ],
    "The Savoy": [
        {"title": "Savoy Single", "capacity": 1},
        {"title": "River King", "capacity": 2},
    ],
    "Hotel Arts Barcelona": [
        {"title": "Sea Single", "capacity": 1},
        {"title": "Mediterranean Double", "capacity": 2},
    ],
    "Grand Hyatt Seoul": [
        {"title": "Seoul Single", "capacity": 1},
        {"title": "Han River Double", "capacity": 2},
    ],
    "The Langham Sydney": [
        {"title": "Harbour Single", "capacity": 1},
        {"title": "Sydney Double", "capacity": 2},
    ],
    "Shangri-La Bangkok": [
        {"title": "River Single", "capacity": 1},
        {"title": "Thai Double", "capacity": 2},
    ],
    "Hotel Adlon Kempinski": [
        {"title": "Berlin Single", "capacity": 1},
        {"title": "Brandenburg Double", "capacity": 2},
    ],
    "Fairmont Banff Springs": [
        {"title": "Mountain Single", "capacity": 1},
        {"title": "Castle Double", "capacity": 2},
    ],
}
